services:
    kanbano:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: kanbano
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.kanbano.rule=Host(`kanbano.fr`) || Host(`www.kanbano.fr`)"
            - "traefik.http.routers.kanbano.entrypoints=web,websecure"
            - "traefik.http.routers.kanbano.tls.certresolver=letsencrypt"
            - "traefik.http.services.kanbano.loadbalancer.server.port=80"
        networks:
            - dokploy-network
        restart: always

networks:
    dokploy-network:
        external: true
