services:
    newsletters:
        build:
            context: .
            dockerfile: ./apps/newsletters/Dockerfile

        environment:
            NODE_ENV: ${NODE_ENV}
            PORT: ${PORT}
            SMTP_HOST: ${SMTP_HOST}
            SMTP_PORT: ${SMTP_PORT}
            SMTP_USER: ${SMTP_USER}
            SMTP_PASS: ${SMTP_PASS}
            SMTP_FROM: ${SMTP_FROM}


        expose:
            - "3000"

        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.newsletters.rule=Host(`api.kanbano.fr`)"
            - "traefik.http.routers.newsletters-http.entrypoints=web"
            - "traefik.http.routers.newsletters-http.middlewares=newsletters-https-redirect"
            - "traefik.http.middlewares.newsletters-https-redirect.redirectscheme.scheme=https"
            - "traefik.http.routers.newsletters.entrypoints=websecure"
            - "traefik.http.routers.newsletters.tls.certresolver=letsencrypt"
            - "traefik.http.services.newsletters.loadbalancer.server.port=3000"

        networks:
            - dokploy-network

        restart: unless-stopped

networks:
    dokploy-network:
        external: true
