services:
    kanbano:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: kanbano
        labels:
            # Activer Traefik
            - "traefik.enable=true"

            # Router HTTPS
            - "traefik.http.routers.kanbano-secure.rule=Host(`kanbano.fr`) || Host(`www.kanbano.fr`)"
            - "traefik.http.routers.kanbano-secure.entrypoints=websecure"
            - "traefik.http.routers.kanbano-secure.tls=true"
            - "traefik.http.routers.kanbano-secure.tls.certresolver=letsencrypt"
            - "traefik.http.routers.kanbano-secure.service=kanbano"

            # Router HTTP (redirection vers HTTPS)
            - "traefik.http.routers.kanbano-http.rule=Host(`kanbano.fr`) || Host(`www.kanbano.fr`)"
            - "traefik.http.routers.kanbano-http.entrypoints=web"
            - "traefik.http.routers.kanbano-http.middlewares=redirect-to-https"

            # Middleware de redirection
            - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
            - "traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true"

            # Service (port du container)
            - "traefik.http.services.kanbano.loadbalancer.server.port=80"

        networks:
            - dokploy-network
        restart: always

networks:
    dokploy-network:
        external: true
