services:
    newsletters:
        build:
            context: .
            dockerfile: ./apps/newsletters/Dockerfile
        container_name: newsletters

        environment:
            PORT: ${PORT}
            NODE_ENV: ${NODE_ENV}
            SMTP_HOST: ${SMTP_HOST}
            SMTP_PORT: ${SMTP_PORT}
            SMTP_USER: ${SMTP_USER}
            SMTP_PASS: ${SMTP_PASS}
            SMTP_FROM: ${SMTP_FROM}

        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.newsletters.rule=Host(`api.kanbano.fr`)"
            - "traefik.http.routers.newsletters.entrypoints=websecure"
            - "traefik.http.routers.newsletters.tls.certresolver=letsencrypt"
            - "traefik.http.services.newsletters.loadbalancer.server.port=3000"

        networks:
            - dokploy-network

        restart: unless-stopped

networks:
    dokploy-network:
        external: true
