services:
    newsletters:
        build:
            context: .
            dockerfile: ./apps/newsletters/Dockerfile
        container_name: newsletters

        env_file: [ ]

        environment:
            NODE_ENV: ${{project.NODE_ENV}}
            PORT: ${{project.PORT}}
            SMTP_HOST: ${{project.SMTP_HOST}}
            SMTP_PORT: ${{project.SMTP_PORT}}
            SMTP_USER: ${{project.SMTP_USER}}
            SMTP_PASS: ${{project.SMTP_PASS}}
            SMTP_FROM: ${{project.SMTP_FROM}}

        expose:
            - "3000"

        labels:
            - "traefik.enable=true"

            # Router HTTPS
            - "traefik.http.routers.newsletters.rule=Host(`api.kanbano.fr`) && PathPrefix(`/newsletters`)"
            - "traefik.http.routers.newsletters.entrypoints=websecure"
            - "traefik.http.routers.newsletters.tls.certresolver=letsencrypt"

            # Service interne (port du container)
            - "traefik.http.services.newsletters.loadbalancer.server.port=3000"

        networks:
            - dokploy-network

        restart: unless-stopped

networks:
    dokploy-network:
        external: true
