[variables]
NIXPACKS_PKGS = "nodejs_20 pnpm"

[phases.install]
cmds = [
  "pnpm install --frozen-lockfile"
]

[phases.build]
cmds = [
  "pnpm exec nx run kanbano:build --configuration=production"
]

[start]
cmd = "npx --yes serve dist/apps/kanbano/browser -s -n -p $PORT"
